#! /usr/bin/env node

var program = require('commander'),
    fs = require('fs'),
    esprima = require('esprima');

program
    .version(require('./package.json').version)
    .usage('<infile> <outfile>')
    .option('-d, --dynamic', 'Use dynamic mode')
    .parse(process.argv);

if (program.args.length !== 1 && program.args.length !== 2) {
    console.error('ngmin should be called with an input and output file, or one arguments if output to stdout');
    process.exit(1);
}

var infile = program.args[0];
try {
    var content = fs.readFileSync(infile, 'utf-8');
} catch(e) {
    console.error('Error opening: ' + infile);
    process.exit(1);
}

var ast = esprima.parse(content);

// TODO
var cSource = ast;

if (program.args.length === 2) {
    var outfile = program.args[1];

    try {
	fs.writeFileSync(outfile, cSource);
    } catch (e) {
	console.error('Error writing to: ' + outfile);
	process.exit(1);
    }

} else {
    console.info(JSON.stringify(cSource));
}
