#! /usr/bin/env node

var program = require('commander'),
    fs = require('fs');

program
    .version(require('./package.json').version)
    .alias('e')
    .description('hello')
    .usage('<infile>')
    .option('-m, --mock <path>', 'function definition file')
    .parse(process.argv);


// mock
var mockFile = program.mock;
if(mockFile !== undefined) {
    try {
	var mock = fs.readFileSync(mockFile, 'utf-8');
	eval(mock);
    } catch(e) {
	console.error('Error opening: ' + infile);
	process.exit(1);
    }
}

// infile
var infile = program.args[0];
try {
    var content = fs.readFileSync(infile, 'utf-8');
    eval(content)
} catch(e) {
    console.error('Error opening: ' + infile);
    process.exit(1);
}

process.exit(0);
